class AppLists {
  /// Nationalities
  static const List<String> nationalities = [
    '🇵🇰 Pakistani',
    '🇮🇳 Indian',
    '🇺🇸 American',
    '🇬🇧 British',
    '🇨🇦 Canadian',
    '🇦🇺 Australian',
    '🇨🇳 Chinese',
    '🇯🇵 Japanese',
    '🇩🇪 German',
    '🇫🇷 French',
    '🇦🇪 Emirati',
    '🇷🇺 Russian',
    '🇧🇷 Brazilian',
    '🇿🇦 South African',
    '🇲🇽 Mexican',
    '🇮🇹 Italian',
    '🇪🇸 Spanish',
    '🇳🇱 Dutch',
    '🇸🇪 Swedish',
    '🇳🇴 Norwegian',
    '🇩🇰 Danish',
    '🇫🇮 Finnish',
    '🇳🇿 New Zealander',
    '🇸🇬 Singaporean',
    '🇲🇾 Malaysian',
    '🇹🇭 Thai',
    '🇮🇩 Indonesian',
    '🇵🇭 Filipino',
    '🇻🇳 Vietnamese',
    '🇰🇷 South Korean',
    '🇸🇦 Saudi',
    '🇹🇷 Turkish',
    '🇪🇬 Egyptian',
    '🇳🇬 Nigerian',
    '🇰🇪 Kenyan',
    '🇬🇭 Ghanaian',
    '🇦🇷 Argentine',
    '🇨🇱 Chilean',
    '🇨🇴 Colombian',
    '🇵🇪 Peruvian',
    '🇻🇪 Venezuelan',
    '🇺🇦 Ukrainian',
    '🇵🇱 Polish',
    '🇬🇷 Greek',
    '🇵🇹 Portuguese',
    '🇨🇭 Swiss',
    '🇧🇪 Belgian',
    '🇦🇹 Austrian',
    '🇮🇪 Irish',
    '🇮🇸 Icelander',
    '🇱🇺 Luxembourger',
  ];

  /// Visa Types
  static const List<String> visaTypes = [
    'Travel',
    'Student',
    'Work',
    'Investment',
  ];

  /// Country Calling Codes
  static const List<String> countryCodes = [
    '+92',
    '+91',
    '+1',
    '+44',
    '+971',
    '+86',
    '+81',
  ];

  /// Countries with text flags and calling codes
  static const List<Map<String, String>> countries = [
    {'name': 'Pakistan', 'flag': '🇵🇰', 'code': '+92'},
    {'name': 'India', 'flag': '🇮🇳', 'code': '+91'},
    {'name': 'United States', 'flag': '🇺🇸', 'code': '+1'},
    {'name': 'United Kingdom', 'flag': '🇬🇧', 'code': '+44'},
    {'name': 'United Arab Emirates', 'flag': '🇦🇪', 'code': '+971'},
    {'name': 'China', 'flag': '🇨🇳', 'code': '+86'},
    {'name': 'Japan', 'flag': '🇯🇵', 'code': '+81'},
    {'name': 'Germany', 'flag': '🇩🇪', 'code': '+49'},
    {'name': 'France', 'flag': '🇫🇷', 'code': '+33'},
    // optional: remove if you want unique +1
    {'name': 'Australia', 'flag': '🇦🇺', 'code': '+61'},
    {'name': 'Brazil', 'flag': '🇧🇷', 'code': '+55'},
    {'name': 'South Africa', 'flag': '🇿🇦', 'code': '+27'},
    {'name': 'Russia', 'flag': '🇷🇺', 'code': '+7'},
    {'name': 'Mexico', 'flag': '🇲🇽', 'code': '+52'},
    {'name': 'Italy', 'flag': '🇮🇹', 'code': '+39'},
    {'name': 'Spain', 'flag': '🇪🇸', 'code': '+34'},
    {'name': 'Netherlands', 'flag': '🇳🇱', 'code': '+31'},
    {'name': 'Sweden', 'flag': '🇸🇪', 'code': '+46'},
    {'name': 'Norway', 'flag': '🇳🇴', 'code': '+47'},
    {'name': 'Denmark', 'flag': '🇩🇰', 'code': '+45'},
    {'name': 'Finland', 'flag': '🇫🇮', 'code': '+358'},
    {'name': 'New Zealand', 'flag': '🇳🇿', 'code': '+64'},
    {'name': 'Singapore', 'flag': '🇸🇬', 'code': '+65'},
    {'name': 'Malaysia', 'flag': '🇲🇾', 'code': '+60'},
    {'name': 'Thailand', 'flag': '🇹🇭', 'code': '+66'},
    {'name': 'Indonesia', 'flag': '🇮🇩', 'code': '+62'},
    {'name': 'Philippines', 'flag': '🇵🇭', 'code': '+63'},
    {'name': 'Vietnam', 'flag': '🇻🇳', 'code': '+84'},
    {'name': 'South Korea', 'flag': '🇰🇷', 'code': '+82'},
    {'name': 'Saudi Arabia', 'flag': '🇸🇦', 'code': '+966'},
    {'name': 'Turkey', 'flag': '🇹🇷', 'code': '+90'},
    {'name': 'Egypt', 'flag': '🇪🇬', 'code': '+20'},
    {'name': 'Nigeria', 'flag': '🇳🇬', 'code': '+234'},
    {'name': 'Kenya', 'flag': '🇰🇪', 'code': '+254'},
    {'name': 'Ghana', 'flag': '🇬🇭', 'code': '+233'},
    {'name': 'Argentina', 'flag': '🇦🇷', 'code': '+54'},
    {'name': 'Chile', 'flag': '🇨🇱', 'code': '+56'},
    {'name': 'Colombia', 'flag': '🇨🇴', 'code': '+57'},
    {'name': 'Peru', 'flag': '🇵🇪', 'code': '+51'},
    {'name': 'Venezuela', 'flag': '🇻🇪', 'code': '+58'},
    {'name': 'Ukraine', 'flag': '🇺🇦', 'code': '+380'},
    {'name': 'Poland', 'flag': '🇵🇱', 'code': '+48'},
    {'name': 'Greece', 'flag': '🇬🇷', 'code': '+30'},
    {'name': 'Portugal', 'flag': '🇵🇹', 'code': '+351'},
    {'name': 'Switzerland', 'flag': '🇨🇭', 'code': '+41'},
    {'name': 'Belgium', 'flag': '🇧🇪', 'code': '+32'},
    {'name': 'Austria', 'flag': '🇦🇹', 'code': '+43'},
    {'name': 'Ireland', 'flag': '🇮🇪', 'code': '+353'},
    {'name': 'Iceland', 'flag': '🇮🇸', 'code': '+354'},
    {'name': 'Luxembourg', 'flag': '🇱🇺', 'code': '+352'},
  ];
}
