class AppLists {
  /// Nationalities
  static const List<String> nationalities = [
    '🇵🇰 Pakistani',
    '🇮🇳 Indian',
    '🇺🇸 American',
    '🇬🇧 British',
    '🇨🇦 Canadian',
    '🇦🇺 Australian',
    '🇨🇳 Chinese',
    '🇯🇵 Japanese',
    '🇩🇪 German',
    '🇫🇷 French',
    '🇦🇪 Emirati',
    '🇷🇺 Russian',
    '🇧🇷 Brazilian',
    '🇿🇦 South African',
    '🇲🇽 Mexican',
    '🇮🇹 Italian',
    '🇪🇸 Spanish',
    '🇳🇱 Dutch',
    '🇸🇪 Swedish',
    '🇳🇴 Norwegian',
    '🇩🇰 Danish',
    '🇫🇮 Finnish',
    '🇳🇿 New Zealander',
    '🇸🇬 Singaporean',
    '🇲🇾 Malaysian',
    '🇹🇭 Thai',
    '🇮🇩 Indonesian',
    '🇵🇭 Filipino',
    '🇻🇳 Vietnamese',
    '🇰🇷 South Korean',
    '🇸🇦 Saudi',
    '🇹🇷 Turkish',
    '🇪🇬 Egyptian',
    '🇳🇬 Nigerian',
    '🇰🇪 Kenyan',
    '🇬🇭 Ghanaian',
    '🇦🇷 Argentine',
    '🇨🇱 Chilean',
    '🇨🇴 Colombian',
    '🇵🇪 Peruvian',
    '🇻🇪 Venezuelan',
    '🇺🇦 Ukrainian',
    '🇵🇱 Polish',
    '🇬🇷 Greek',
    '🇵🇹 Portuguese',
    '🇨🇭 Swiss',
    '🇧🇪 Belgian',
    '🇦🇹 Austrian',
    '🇮🇪 Irish',
    '🇮🇸 Icelander',
    '🇱🇺 Luxembourger',
  ];

  /// Visa Types
  static const List<String> visaTypes = [
    'Travel',
    'Student',
    'Work',
    'Investment',
    'Business',
    'Tourist',
  ];

  /// Country Calling Codes
  static const List<String> countryCodes = [
    '+92',
    '+91',
    '+1',
    '+44',
    '+971',
    '+86',
    '+81',
  ];

  /// Countries with text flags and calling codes
  static const List<Map<String, String>> countries = [
    {'name': 'Pakistan', 'flag': '🇵🇰', 'code': '+92'},
    {'name': 'India', 'flag': '🇮🇳', 'code': '+91'},
    {'name': 'United States', 'flag': '🇺🇸', 'code': '+1'},
    {'name': 'United Kingdom', 'flag': '🇬🇧', 'code': '+44'},
    {'name': 'United Arab Emirates', 'flag': '🇦🇪', 'code': '+971'},
    {'name': 'China', 'flag': '🇨🇳', 'code': '+86'},
    {'name': 'Japan', 'flag': '🇯🇵', 'code': '+81'},
    {'name': 'Germany', 'flag': '🇩🇪', 'code': '+49'},
    {'name': 'France', 'flag': '🇫🇷', 'code': '+33'},
    {'name': 'Canada', 'flag': '🇨🇦', 'code': '+1'},
    {'name': 'Australia', 'flag': '🇦🇺', 'code': '+61'},
    {'name': 'Brazil', 'flag': '🇧🇷', 'code': '+55'},
    {'name': 'South Africa', 'flag': '🇿🇦', 'code': '+27'},
    {'name': 'Russia', 'flag': '🇷🇺', 'code': '+7'},
    {'name': 'Mexico', 'flag': '🇲🇽', 'code': '+52'},
    {'name': 'Italy', 'flag': '🇮🇹', 'code': '+39'},
    {'name': 'Spain', 'flag': '🇪🇸', 'code': '+34'},
    {'name': 'Netherlands', 'flag': '🇳🇱', 'code': '+31'},
    {'name': 'Sweden', 'flag': '🇸🇪', 'code': '+46'},
    {'name': 'Norway', 'flag': '🇳🇴', 'code': '+47'},
    {'name': 'Denmark', 'flag': '🇩🇰', 'code': '+45'},
    {'name': 'Finland', 'flag': '🇫🇮', 'code': '+358'},
    {'name': 'New Zealand', 'flag': '🇳🇿', 'code': '+64'},
    {'name': 'Singapore', 'flag': '🇸🇬', 'code': '+65'},
    {'name': 'Malaysia', 'flag': '🇲🇾', 'code': '+60'},
    {'name': 'Thailand', 'flag': '🇹🇭', 'code': '+66'},
    {'name': 'Indonesia', 'flag': '🇮🇩', 'code': '+62'},
    {'name': 'Philippines', 'flag': '🇵🇭', 'code': '+63'},
    {'name': 'Vietnam', 'flag': '🇻🇳', 'code': '+84'},
    {'name': 'South Korea', 'flag': '🇰🇷', 'code': '+82'},
    {'name': 'Saudi Arabia', 'flag': '🇸🇦', 'code': '+966'},
    {'name': 'Turkey', 'flag': '🇹🇷', 'code': '+90'},
    {'name': 'Egypt', 'flag': '🇪🇬', 'code': '+20'},
    {'name': 'Nigeria', 'flag': '🇳🇬', 'code': '+234'},
    {'name': 'Kenya', 'flag': '🇰🇪', 'code': '+254'},
    {'name': 'Ghana', 'flag': '🇬🇭', 'code': '+233'},
    {'name': 'Argentina', 'flag': '🇦🇷', 'code': '+54'},
    {'name': 'Chile', 'flag': '🇨🇱', 'code': '+56'},
    {'name': 'Colombia', 'flag': '🇨🇴', 'code': '+57'},
    {'name': 'Peru', 'flag': '🇵🇪', 'code': '+51'},
    {'name': 'Venezuela', 'flag': '🇻🇪', 'code': '+58'},
    {'name': 'Ukraine', 'flag': '🇺🇦', 'code': '+380'},
    {'name': 'Poland', 'flag': '🇵🇱', 'code': '+48'},
    {'name': 'Greece', 'flag': '🇬🇷', 'code': '+30'},
    {'name': 'Portugal', 'flag': '🇵🇹', 'code': '+351'},
    {'name': 'Switzerland', 'flag': '🇨🇭', 'code': '+41'},
    {'name': 'Belgium', 'flag': '🇧🇪', 'code': '+32'},
    {'name': 'Austria', 'flag': '🇦🇹', 'code': '+43'},
    {'name': 'Ireland', 'flag': '🇮🇪', 'code': '+353'},
    {'name': 'Iceland', 'flag': '🇮🇸', 'code': '+354'},
    {'name': 'Luxembourg', 'flag': '🇱🇺', 'code': '+352'},
    {'name': 'Czech Republic', 'flag': '🇨🇿', 'code': '+420'},
    {'name': 'Hungary', 'flag': '🇭🇺', 'code': '+36'},
    {'name': 'Romania', 'flag': '🇷🇴', 'code': '+40'},
    {'name': 'Bulgaria', 'flag': '🇧🇬', 'code': '+359'},
    {'name': 'Slovakia', 'flag': '🇸🇰', 'code': '+421'},
    {'name': 'Slovenia', 'flag': '🇸🇮', 'code': '+386'},
    {'name': 'Croatia', 'flag': '🇭🇷', 'code': '+385'},
    {'name': 'Serbia', 'flag': '🇷🇸', 'code': '+381'},
    {'name': 'Bosnia & Herzegovina', 'flag': '🇧🇦', 'code': '+387'},
    {'name': 'Montenegro', 'flag': '🇲🇪', 'code': '+382'},
    {'name': 'North Macedonia', 'flag': '🇲🇰', 'code': '+389'},
    {'name': 'Albania', 'flag': '🇦🇱', 'code': '+355'},
    {'name': 'Lithuania', 'flag': '🇱🇹', 'code': '+370'},
    {'name': 'Latvia', 'flag': '🇱🇻', 'code': '+371'},
    {'name': 'Estonia', 'flag': '🇪🇪', 'code': '+372'},
    {'name': 'Belarus', 'flag': '🇧🇾', 'code': '+375'},
    {'name': 'Moldova', 'flag': '🇲🇩', 'code': '+373'},
    {'name': 'Georgia', 'flag': '🇬🇪', 'code': '+995'},
    {'name': 'Armenia', 'flag': '🇦🇲', 'code': '+374'},
    {'name': 'Azerbaijan', 'flag': '🇦🇿', 'code': '+994'},
    {'name': 'Kazakhstan', 'flag': '🇰🇿', 'code': '+7'},
    {'name': 'Uzbekistan', 'flag': '🇺🇿', 'code': '+998'},
    {'name': 'Kyrgyzstan', 'flag': '🇰🇬', 'code': '+996'},
    {'name': 'Tajikistan', 'flag': '🇹🇯', 'code': '+992'},
    {'name': 'Turkmenistan', 'flag': '🇹🇲', 'code': '+993'},
    {'name': 'Afghanistan', 'flag': '🇦🇫', 'code': '+93'},
    {'name': 'Bangladesh', 'flag': '🇧🇩', 'code': '+880'},
    {'name': 'Nepal', 'flag': '🇳🇵', 'code': '+977'},
    {'name': 'Sri Lanka', 'flag': '🇱🇰', 'code': '+94'},
    {'name': 'Bhutan', 'flag': '🇧🇹', 'code': '+975'},
    {'name': 'Maldives', 'flag': '🇲🇻', 'code': '+960'},
    {'name': 'Singapore', 'flag': '🇸🇬', 'code': '+65'},
    {'name': 'Brunei', 'flag': '🇧🇳', 'code': '+673'},
    {'name': 'Malaysia', 'flag': '🇲🇾', 'code': '+60'},
    {'name': 'Thailand', 'flag': '🇹🇭', 'code': '+66'},
    {'name': 'Vietnam', 'flag': '🇻🇳', 'code': '+84'},
    {'name': 'Cambodia', 'flag': '🇰🇭', 'code': '+855'},
    {'name': 'Laos', 'flag': '🇱🇦', 'code': '+856'},
    {'name': 'Myanmar', 'flag': '🇲🇲', 'code': '+95'},
    {'name': 'Mongolia', 'flag': '🇲🇳', 'code': '+976'},
  ];
}
